name: SigmaLevels
version: @version@
authors: [DevTuca, DevKeni]
loadbefore: [SigmaGems]
main: com.serversigma.sigmalevels.SigmaLevels

commands:
  pickaxe:
    permission-message: "§cVocê não tem permissão para utilizar esse comando."
    permission: "sigmalevels.pickaxe.give"
    aliases: [picareta]

  sword:
    aliases: [espada]
    permission-message: "§cVocê não tem permissão para utilizar esse comando."
    permission: "sigmalevels.sword.give"

  armor:
    aliases: [armadura]
    permission-message: "§cVocê não tem permissão para utilizar esse comando."
    permission: "sigmalevels.armor.give"